### ISSUE TITLE
core/pgAdmin is slow 

### ISSUE THREAD

**Issue by braaar** [ayrorg/infra#20]
pgAdmin is performing very slowly. Establishing connections takes a very long time. I have gotten some errors where it is complaining that there are not enough free connections available. I think we need to look into connection pooling and make connections close when not in use and such.

**Comment by braaar** [comment]
It hangs when attempting to edit data through pgAdmin.

**Comment by braaar** [comment]
Right now I can't seem to even open the server list to connect to a server. pgAdmin is completely knackered.

**Comment by braaar** [comment]
![Screenshot 2022-01-27 at 12 04 59](https://user-images.githubusercontent.com/5765650/151337123-0a103020-f43b-453e-923a-50f852e85b13.jpg)

**Comment by braaar** [comment]
Can't see the dashboard
![Screenshot 2022-01-27 at 12 06 47](https://user-images.githubusercontent.com/5765650/151337413-cbfc3332-f3f7-40a4-be46-ffd46f33ee65.jpg)

**Comment by braaar** [comment]
The database itself seems okay. Client application can fetch data as expected.

**Comment by braaar** [comment]
Justs got this error when attempting to log in to pgAdmin
![Screenshot 2022-01-27 at 16 41 32](https://user-images.githubusercontent.com/5765650/151381116-13fc858b-021e-41cb-b010-7d787f01a374.jpg)

**Comment by cobraz** [comment]
Attemted to fix pgadmin today. Please reopen this if it still doesn't work :)

Seemed like we bumped to a newer version, which failed. I've locked our pgadmin to a specific version now.
